# Generated by Django 5.1.4 on 2025-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField(default=0)),
                ("data", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PROGRES", "In Progress"), ("FINISHED", "Completed")],
                        default="PROGRESS",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
